# Dependencies
markdown:         kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      rouge

# Permalinks
permalink:           pretty

# Setup
title:            chaosplay
tagline:          'A blog'
description:      'Random thoughts about programming, philosophy, history, video games, photography, &amp; life.'
url:              http://chaosplay.com
baseurl:          /

author:
  name:           'Amer'
  url:            

paginate:         10
     
